=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/5 Repaso Inventario/inventario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="idiomas">
    <xs:restriction base="xs:string">
        <xs:enumeration value="ES"/>
        <xs:enumeration value="EN"/>
        <xs:enumeration value="FR"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="codigoPatron">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{3}[a-z]{2}"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="intervaloPeso">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="50"/>
        <xs:maxInclusive value="1500"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="listaarticulos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="articulo" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="codigo" type="codigoPatron"/>
                    <xs:element name="peso" type="intervaloPeso"/>
                    <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
                    <!-- Para que se sea opcional usa minOccurs = 0-->
                    <!-- Mixed = true para que tenga cualquier dato y cantidad-->
                    <xs:element name="cantidad" minOccurs="0">
                        <xs:complexType mixed="true">
                            <xs:attribute name="unidad" type="xs:string" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="idioma" type="idiomas" use="optional"/>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/5 Repaso Inventario/repaso_inventario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Dentro de listaarticulos hay entre 2 y 6 articulos-->
<listaarticulos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="inventario.xsd">
    <!--Todo articulo lleva un código, a veces una descripción
    y siempre un peso-->
    <!--EL idioman siempre lleva un atributo
            idioma que solo puede ser ES, EN o FR-->
    <articulo idioma="ES">
        <!--El código siempre es 3 cifras y dos minúsculas Patrón: \d{3}[a-z]{2}-->
        <codigo>719cf</codigo>
        <!--El peso siempre está entre 50 y 1500-->
        <peso>640</peso> 
        <cantidad unidad="litros">20</cantidad>
    </articulo>
    <articulo>
        <codigo>904ps</codigo>
        <peso>1499</peso>
    </articulo>
</listaarticulos>
