=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/4 Expedientes/expedientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="cursos">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Primero"/>
            <xs:enumeration value="Segundo"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="expedientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="expediente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulacion" type="xs:string"/>
                            <xs:element name="estudiante" type="xs:string"/>
                            <xs:element name="modulos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modulo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nombre" type="xs:string" use="required"/>
                                                <xs:attribute name="aprobado" type="xs:boolean" use="required"/>
                                                <xs:attribute name="curso" type="cursos" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/4 Expedientes/expedientes (1).xml
<?xml version="1.0" encoding="UTF-8"?>
<expedientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="expedientes.xsd">
    <expediente>
        <titulacion>DAM</titulacion>
        <estudiante>Ainhoa Gárate Lizarraga</estudiante>
        <modulos>
            <modulo nombre="Sistemas Informáticos" aprobado="true" curso="Primero" />
            <modulo nombre="Lenguajes de Marcas y Sistemas de Gestión de la Información" aprobado="true" curso="Primero"/>
            <modulo nombre="Programación multimedia y dispositivos móviles" aprobado="false" curso="Segundo" />
        </modulos>
    </expediente>
    <expediente>
        <titulacion>DAW</titulacion>
        <estudiante>Ferran Soler Puig</estudiante>
        <modulos>
            <modulo nombre="Programación" aprobado="true" curso="Primero" />
            <modulo nombre="Desarrollo web en entorno cliente" aprobado="false" curso="Segundo" />
        </modulos>
    </expediente>
</expedientes>
