=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/2 Expedientes simple/expediente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="expedientes">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="expediente" minOccurs="1" maxOccurs="7">
            <xs:complexType>
                <xs:sequence>
                <xs:element name="titulacion"></xs:element>
                <xs:element name="estudiante"></xs:element>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo" maxOccurs="unbounded" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                </xs:sequence>
                <xs:attribute name="codigo" type="xs:integer" use="required"></xs:attribute>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/2 Expedientes simple/expedientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<expedientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="expediente.xsd">
    <expediente codigo="123456">
        <titulacion>DAM</titulacion>
        <estudiante>Ainhoa Gárate Lizarraga</estudiante>
        <modulos>
            <modulo>Sistemas Informáticos</modulo> 
            <modulo>Lenguajes de Marcas y Sistemas de Gestión de la Información</modulo>
            <modulo>Programación multimedia y dispositivos móviles</modulo>
        </modulos>
    </expediente>
    <expediente codigo="654321">
        <titulacion>DAW</titulacion>
        <estudiante>Ferran Soler Puig</estudiante>
        <modulos>
            <modulo>Programación</modulo> 
            <modulo>Desarrollo web en entorno cliente</modulo> 
        </modulos>
    </expediente>
</expedientes>
