<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareLibre [
  <!ELEMENT softwareLibre (licencias, aplicaciones)>
  <!ELEMENT licencias (licencia*)>
  <!ELEMENT licencia EMPTY>
  <!ELEMENT aplicaciones (aplicacion*)>
  <!ELEMENT aplicacion (version*)>
  <!ELEMENT version EMPTY>
  <!ATTLIST licencia nombre CDATA #REQUIRED>
  <!ATTLIST aplicacion nombre CDATA #REQUIRED>
  <!ATTLIST version nombre CDATA #REQUIRED
					licencia CDATA #REQUIRED
					fechaPublicación CDATA #REQUIRED>
]>
<softwareLibre>
  <licencias>
    <licencia nombre="GPL v2" />
    <licencia nombre="BSD2" />
    <licencia nombre="Apache v2" />
  </licencias>
  <aplicaciones>
    <aplicacion nombre="Inkscape">
      <version nombre="0.47" licencia="GPL v2" fechaPublicación="17/08/2010" />
      <version nombre="0.48" licencia="GPL v2" fechaPublicación="17/08/2010" />
      <version nombre="0.48.2" licencia="GPL v2" fechaPublicación="14/08/2011" />
    </aplicacion>
    <aplicacion nombre="PostgreSQL">
      <version nombre="9.1.0" licencia="BSD2" fechaPublicación="15/09/2011" />
      <version nombre="9.1.3" licencia="BSD2" fechaPublicación="09/04/2025"/>
    </aplicacion>
  </aplicaciones>
</softwareLibre> 
