=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/1. Elementos y Subelementos/Series/series.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="serie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="creador" type="xs:string"/>
                            <xs:element name="genero" type="xs:string"/>
                            <xs:element name="temporadas" type="xs:integer" minOccurs="1"/>
                            <xs:element name="disponibleEnStreaming" type="xs:boolean" default="false"/>
                            <xs:element name="clasificacion" type="xs:string"/>
                        </xs:all>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                        <xs:attribute name="year" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ramom06/DAW/Primero/Lenguaje-de-marca/Tema4/xml-Schema/1. Elementos y Subelementos/Series/series.xml
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="series.xsd">
    <serie id="123" year="2008">
    <titulo>Breaking Bad</titulo>
    <creador>Vince Gilligan</creador>
    <genero>Drama</genero>
    <temporadas>5</temporadas>
    <disponibleEnStreaming>true</disponibleEnStreaming>
    <clasificacion>TV-MA</clasificacion>
    </serie>
    <serie id="432" year="2016">
    <titulo>Stranger Things</titulo>
    <creador>Duffer Brothers</creador>
    <genero>Ciencia Ficci√≥n</genero>
    <temporadas>4</temporadas>
    <disponibleEnStreaming>true</disponibleEnStreaming>
    <clasificacion>TV-14</clasificacion>
    </serie>
</catalogo>
